
# This is a patch which disables the strict validation of path type in Ingress resources
# Otherwise the dots (.) in our gRPC service names will cause the Ingress to fail validation
# See: https://github.com/kubernetes/ingress-nginx/issues/11176
apiVersion: v1
data:
  strict-validate-path-type: "false"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.12.3
  name: ingress-nginx-controller
  namespace: ingress-nginx
