name: pr-checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
  merge_group:

jobs:
  build-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          submodules: recursive

      - name: Enable Corepack
        run: corepack enable

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn build

      - name: Test
        run: make test
